tables:
  onlines:
    fields:
      id: 'string'
      guestKey: 'string'
      channelId: 'string'
      expiresAt: 'integer'
      lastSeen: 'integer'
    expireKey: 'expiresAt'
    hashKey: 'channelId'
    sortKey: 'id'
    subIndices:
      guest:
        hashKey: 'channelId'
        sortKey: 'lastSeen'
    stream:
      adaptor: 'amqp'
      queue: 'online'

adaptors:
  amqp:
    driver: 'rabbitmq'
    url: 'amqp://guest:guest@localhost:5672/'