tables:
  onlines:
    fields:
      id: 'string'
      guestKey: 'string'
      channelId: 'string'
      expiresAt: 'integer'
      lastSeen: 'integer'
    expireKey: 'expiresAt'
    hashKey: 'channelId'
    sortKey: 'id'
    subIndices:
      guest: 'lastSeen'
    metrics:
      table: 'onlines-metrics'
      ttl: 60
      interval: 2

  onlines-metrics:
    fields:
      channelId: 'string'
      time: 'integer'
      value: 'integer'
      expiresAt: 'integer'
    expireKey: 'expiresAt'
    hashKey: 'channelId'
    sortKey: 'time'

  _metrics:
    fields:
      key: 'string'
      time: 'integer'
      value: 'integer'
      expiresAt: 'integer'
    expireKey: 'expiresAt'
    hashKey: 'key'
    sortKey: 'time'

# scan
# get_tpm
# put_tpm
# size
# expire
