tables:
  onlines:
    fields:
      channelId: 'string'
      personKey: 'string'
      expiresAt: 'integer'
      updatedAt: 'integer'
    expireKey: 'expiresAt'
    hashKey: 'channelId'
    sortKey: 'personKey'
    subIndices:
      guest:
        hashKey: 'channelId'
        sortKey: 'updatedAt'
    metrics:
      table: 'onlines-metrics'
      ttl: 600
      interval: 2

  onlines-metrics:
    fields:
      channelId: 'string'
      time: 'integer'
      value: 'integer'
      expiresAt: 'integer'
    expireKey: 'expiresAt'
    hashKey: 'channelId'
    sortKey: 'time'

  sockets:
    fields:
      id: 'string'
      personKey: 'string'
      expiresAt: 'integer'
    expireKey: 'expiresAt'
    hashKey: 'id'
    subIndices:
      person:
        hashKey: 'personKey'
    metrics:
      table: 'sockets-metrics'
      ttl: 600
      interval: 2

  sockets-metrics:
    fields:
      id: 'string'
      time: 'integer'
      value: 'integer'
      expiresAt: 'integer'
    expireKey: 'expiresAt'
    hashKey: 'id'
    sortKey: 'time'

  _metrics:
    fields:
      key: 'string'
      time: 'integer'
      value: 'integer'
      expiresAt: 'integer'
    expireKey: 'expiresAt'
    hashKey: 'key'
    sortKey: 'time'