server:
  addr: ':8000'
  logging: true
  mode: 'debug'

tables:
  onlines:
    fields:
      channelId: 'string'
      personKey: 'string'
      expiresAt: 'integer'
      updatedAt: 'integer'
    expireKey: 'expiresAt'
    hashKey: 'channelId'
    sortKey: 'personKey'
    subIndices:
      guest:
        hashKey: 'channelId'
        sortKey: 'updatedAt'
    metrics:
      ttl: 600000
      interval: 2000
      expireKey: 'expiresAt'
      count: 'value'
      time: 'createdAt'

  sockets:
    fields:
      id: 'string'
      personKey: 'string'
      expiresAt: 'integer'
    expireKey: 'expiresAt'
    hashKey: 'id'
    subIndices:
      person:
        hashKey: 'personKey'
    metrics:
      ttl: 600000
      interval: 2000

test: 'ok'