tables:
  onlines:
    fields:
      channelId: 'string'
      personKey: 'string'
      expiresAt: 'integer'
      updatedAt: 'integer'
    expireKey: 'expiresAt'
    hashKey: 'channelId'
    sortKey: 'personKey'
    subIndices:
      guest:
        hashKey: 'channelId'
        sortKey: 'updatedAt'
  tests:
    fields:
      hash: 'integer'
      sort: 'integer'
      expiresAt: 'integer'
    hashKey: 'hash'
    sortKey: 'sort'
    expireKey: 'expiresAt'
    subIndices:
      index:
        hashKey: 'hash'
