tables:
  onlines:
    fields:
      channelId: 'string'
      personKey: 'string'
      expiresAt: 'integer'
      updatedAt: 'integer'
    expireKey: 'expiresAt'
    hashKey: 'channelId'
    sortKey: 'personKey'
    subIndices:
      guest:
        hashKey: 'channelId'
        sortKey: 'updatedAt'
    metrics:
      table: 'onlines-metrics'
      ttl: 600
      interval: 2